// Structured schema definition used for AI fill requests.
// Field names intentionally mirror the editor's camelCase model so AI payloads
// can be merged directly into the in-memory Plant shape.
export const plantSchema = {
  plantType: 'enum',
  utility: 'enum[]',
  comestiblePart: 'enum[]',
  fruitType: 'enum[]',
  seasons: 'enum[]',
  description: 'longtext',
  identity: {
    name: 'text',
    plantType: 'enum',
    utility: 'enum[]',
    comestiblePart: 'enum[]',
    fruitType: 'enum[]',
    givenNames: 'tag[]',
    commonNames: 'tag[]',
    synonyms: 'tag[]',
    scientificName: 'text',
    canonicalName: 'text',
    family: 'text',
    genus: 'text',
    taxonRank: 'text',
    cultivarGroup: 'text',
    cultivar: 'text',
    overview: 'longtext',
    promotionMonth: 'int',
    lifeCycle: 'enum',
    season: 'enum[]',
    foliagePersistance: 'enum',
    spiked: 'boolean',
    toxicityHuman: 'enum',
    toxicityPets: 'enum',
    allergens: 'tag[]',
    colors: 'color[]',
    multicolor: 'boolean',
    bicolor: 'boolean',
    scent: 'boolean',
    symbolism: 'tag[]',
    livingSpace: 'enum',
    composition: 'enum[]',
    maintenanceLevel: 'enum',
    externalIds: 'dict',
  },
  plantCare: {
    origin: 'tag[]',
    habitat: 'enum[]',
    temperatureMax: 'int',
    temperatureMin: 'int',
    temperatureIdeal: 'int',
    levelSun: 'enum',
    hygrometry: 'int',
    watering: {
      season: 'enum',
      quantity: 'int',
      timePeriod: 'enum',
    },
    wateringType: 'enum[]',
    division: 'enum[]',
    soil: 'enum[]',
    adviceSoil: 'text',
    mulching: 'enum[]',
    adviceMulching: 'text',
    nutritionNeed: 'enum[]',
    fertilizer: 'enum[]',
    adviceFertilizer: 'text',
  },
  growth: {
    sowingMonth: 'enum[]',
    floweringMonth: 'enum[]',
    fruitingMonth: 'enum[]',
    height: 'int',
    wingspan: 'int',
    tutoring: 'boolean',
    adviceTutoring: 'longtext',
    sowType: 'enum[]',
    separation: 'int',
    transplanting: 'boolean',
    adviceSowing: 'longtext',
    cut: 'text',
  },
  usage: {
    adviceMedicinal: 'longtext',
    nutritionalIntake: 'tag[]',
    infusion: 'boolean',
    adviceInfusion: 'longtext',
    infusionMix: 'dict[]',
    recipesIdeas: 'tag[]',
    aromatherapy: 'boolean',
    spiceMixes: 'tag[]',
  },
  ecology: {
    melliferous: 'boolean',
    polenizer: 'enum[]',
    beFertilizer: 'boolean',
    groundEffect: 'text',
    conservationStatus: 'enum',
  },
  danger: {
    pests: 'tag[]',
    diseases: 'tag[]',
  },
  miscellaneous: {
    companions: 'tag[]',
    tags: 'tag[]',
    sources: 'dict[]',
  },
  meta: {
    status: 'enum',
    funFact: 'text',
    adminCommentary: 'longtext',
    createdBy: 'text',
    createdTime: 'timestamp',
    updatedBy: 'text',
    updatedTime: 'timestamp',
    sourceReferences: 'tag[]',
  },
} as const

export type PlantSchema = typeof plantSchema
