// Structured schema definition used for AI fill requests.
// This mirrors the columnar plant model (no legacy JSON) with categories and fields.
export const plantSchema = {
  plantType: 'enum',
  utility: 'enum[]',
  comestiblePart: 'enum[]',
  fruitType: 'enum[]',
  seasons: 'enum[]',
  description: 'longtext',
  identity: {
    name: 'text',
    plant_type: 'enum',
    utility: 'enum[]',
    comestible_part: 'enum[]',
    fruit_type: 'enum[]',
    given_names: 'tag[]',
    scientific_name: 'text',
    family: 'text',
    overview: 'longtext',
    promotion_month: 'enum',
    life_cycle: 'enum',
    season: 'enum[]',
    foliage_persistence: 'enum',
    spiked: 'boolean',
    toxicity_human: 'enum',
    toxicity_pets: 'enum',
    allergens: 'tag[]',
    colors: 'color[]',
    multicolor: 'boolean',
    bicolor: 'boolean',
    scent: 'boolean',
    symbolism: 'tag[]',
    living_space: 'enum',
    composition: 'enum[]',
    maintenance_level: 'enum',
  },
  plantCare: {
    origin: 'tag[]',
    habitat: 'enum[]',
    temperature_max: 'int',
    temperature_min: 'int',
    temperature_ideal: 'int',
    level_sun: 'enum',
    hygrometry: 'int',
    watering: {
      season: 'enum',
      quantity: 'int',
      time_period: 'enum',
    },
    watering_type: 'enum[]',
    division: 'enum[]',
    soil: 'enum[]',
    advice_soil: 'text',
    mulching: 'enum[]',
    advice_mulching: 'text',
    nutrition_need: 'enum[]',
    fertilizer: 'enum[]',
    advice_fertilizer: 'text',
  },
  growth: {
    sowing_month: 'enum[]',
    flowering_month: 'enum[]',
    fruiting_month: 'enum[]',
    height: 'int',
    wingspan: 'int',
    tutoring: 'boolean',
    advice_tutoring: 'longtext',
    sow_type: 'enum[]',
    separation: 'int',
    transplanting: 'boolean',
    advice_sowing: 'longtext',
    cut: 'text',
  },
  usage: {
    advice_medicinal: 'longtext',
    nutritional_intake: 'tag[]',
    infusion: 'boolean',
    advice_infusion: 'longtext',
    infusion_mix: 'dict[]',
    recipes_ideas: 'tag[]',
    aromatherapy: 'boolean',
    spice_mixes: 'tag[]',
  },
  ecology: {
    melliferous: 'boolean',
    polenizer: 'enum[]',
    be_fertilizer: 'boolean',
    ground_effect: 'text',
    conservation_status: 'enum',
  },
  danger: {
    pests: 'tag[]',
    diseases: 'tag[]',
  },
  miscellaneous: {
    companions: 'uuid[]',
    tags: 'tag[]',
    sources: 'dict[]',
  },
  meta: {
    status: 'enum',
    admin_commentary: 'longtext',
    created_by: 'text',
    created_time: 'timestamp',
    updated_by: 'text',
    updated_time: 'timestamp',
  },
} as const

export type PlantSchema = typeof plantSchema
