import * as React from "react"
import confetti from "canvas-confetti"
import {
  Send,
  Loader2,
  RefreshCw,
  AlertTriangle,
  CheckCircle2,
  Calendar,
  Image as ImageIcon,
} from "lucide-react"

import { Button } from "@/components/ui/button"
import { Select } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog"
import { buildAdminRequestHeaders } from "@/lib/adminAuth"

type BufferOrganization = { id: string; name: string }
type BufferChannel = { id: string; name: string; service: string }
type ScheduleResult = {
  channelId: string
  ok: boolean
  post?: { id: string; text: string; dueAt?: string | null }
  error?: string
}

const SUPPORTED_SERVICES = ["instagram", "facebook", "twitter"] as const
type SupportedService = (typeof SUPPORTED_SERVICES)[number]

const SERVICE_LABELS: Record<string, string> = {
  instagram: "Instagram",
  facebook: "Facebook",
  twitter: "Twitter / X",
}

function isSupportedService(service: string): service is SupportedService {
  return (SUPPORTED_SERVICES as readonly string[]).includes(service)
}

function pad2(n: number): string {
  return n < 10 ? `0${n}` : `${n}`
}

function toLocalInputValue(d: Date): string {
  const yyyy = d.getFullYear()
  const mm = pad2(d.getMonth() + 1)
  const dd = pad2(d.getDate())
  const hh = pad2(d.getHours())
  const mi = pad2(d.getMinutes())
  return `${yyyy}-${mm}-${dd}T${hh}:${mi}`
}

function fireConfettiBurst() {
  const duration = 1200
  const end = Date.now() + duration
  const colors = ["#4ade80", "#22c55e", "#16a34a", "#facc15", "#f97316", "#ef4444", "#8b5cf6", "#3b82f6"]
  const frame = () => {
    confetti({ particleCount: 4, angle: 60, spread: 70, origin: { x: 0, y: 0.7 }, colors })
    confetti({ particleCount: 4, angle: 120, spread: 70, origin: { x: 1, y: 0.7 }, colors })
    if (Date.now() < end) requestAnimationFrame(frame)
  }
  confetti({ particleCount: 140, spread: 90, startVelocity: 45, origin: { x: 0.5, y: 0.5 }, colors })
  frame()
}

const SCHEDULE_PRESETS: Array<{ label: string; minutesFromNow: number }> = [
  { label: "In 1 hour", minutesFromNow: 60 },
  { label: "In 3 hours", minutesFromNow: 180 },
  { label: "Tomorrow 9 AM", minutesFromNow: -1 },
  { label: "Next Monday 9 AM", minutesFromNow: -2 },
]

function presetToDate(label: string, minutesFromNow: number): Date {
  const now = new Date()
  if (minutesFromNow >= 0) return new Date(now.getTime() + minutesFromNow * 60 * 1000)
  if (label === "Tomorrow 9 AM") {
    const d = new Date(now)
    d.setDate(d.getDate() + 1)
    d.setHours(9, 0, 0, 0)
    return d
  }
  if (label === "Next Monday 9 AM") {
    const d = new Date(now)
    const day = d.getDay()
    const diff = ((1 - day + 7) % 7) || 7
    d.setDate(d.getDate() + diff)
    d.setHours(9, 0, 0, 0)
    return d
  }
  return now
}

function canvasToBlob(canvas: HTMLCanvasElement, type = "image/png"): Promise<Blob> {
  return new Promise((resolve, reject) => {
    canvas.toBlob((b) => {
      if (b) resolve(b)
      else reject(new Error("Canvas to blob conversion failed (canvas may be tainted)"))
    }, type)
  })
}

export type AdminExportBufferScheduleProps = {
  /** Full caption text generated by the AI (post body + URLs + hashtags). */
  caption: string
  /** Canvas refs for the 4 generated cards. Each is converted to a PNG and
   * attached to the Buffer post as media. */
  previewRefs: React.MutableRefObject<Array<HTMLCanvasElement | null>>
  /** Plant name used for friendly UI strings. */
  plantName?: string | null
  /** Disable the whole section (e.g. while the bundle is regenerating). */
  disabled?: boolean
}

export const AdminExportBufferSchedule: React.FC<AdminExportBufferScheduleProps> = ({
  caption,
  previewRefs,
  plantName,
  disabled,
}) => {
  const [organizations, setOrganizations] = React.useState<BufferOrganization[]>([])
  const [organizationId, setOrganizationId] = React.useState<string>("")
  const [orgLoading, setOrgLoading] = React.useState(false)
  const [orgError, setOrgError] = React.useState<string>("")

  const [channels, setChannels] = React.useState<BufferChannel[]>([])
  const [channelsLoading, setChannelsLoading] = React.useState(false)
  const [channelsError, setChannelsError] = React.useState<string>("")
  const [selectedChannels, setSelectedChannels] = React.useState<Record<string, boolean>>({})

  const initialSchedule = React.useMemo(() => toLocalInputValue(new Date(Date.now() + 60 * 60 * 1000)), [])
  const [scheduleAt, setScheduleAt] = React.useState<string>(initialSchedule)
  const [addToQueue, setAddToQueue] = React.useState(false)

  const [submitting, setSubmitting] = React.useState(false)
  const [submitError, setSubmitError] = React.useState<string>("")
  const [results, setResults] = React.useState<ScheduleResult[] | null>(null)
  const [showSuccess, setShowSuccess] = React.useState(false)

  const loadOrganizations = React.useCallback(async () => {
    setOrgLoading(true)
    setOrgError("")
    try {
      const headers = await buildAdminRequestHeaders({ Accept: "application/json" })
      const resp = await fetch("/api/admin/buffer/organizations", { headers })
      const data = await resp.json().catch(() => ({}))
      if (!resp.ok) throw new Error(data?.error || `Failed (${resp.status})`)
      const orgs: BufferOrganization[] = Array.isArray(data?.organizations) ? data.organizations : []
      setOrganizations(orgs)
      setOrganizationId((prev) => prev || (orgs[0]?.id ?? ""))
    } catch (e) {
      setOrgError(e instanceof Error ? e.message : "Failed to load organizations")
    } finally {
      setOrgLoading(false)
    }
  }, [])

  const loadChannels = React.useCallback(async (orgId: string) => {
    if (!orgId) return
    setChannelsLoading(true)
    setChannelsError("")
    try {
      const headers = await buildAdminRequestHeaders({ Accept: "application/json" })
      const resp = await fetch(`/api/admin/buffer/channels?organizationId=${encodeURIComponent(orgId)}`, { headers })
      const data = await resp.json().catch(() => ({}))
      if (!resp.ok) throw new Error(data?.error || `Failed (${resp.status})`)
      const all: BufferChannel[] = Array.isArray(data?.channels) ? data.channels : []
      const filtered = all.filter((c) => isSupportedService((c.service || "").toLowerCase()))
      setChannels(filtered)
      const next: Record<string, boolean> = {}
      filtered.forEach((c) => { next[c.id] = true })
      setSelectedChannels(next)
    } catch (e) {
      setChannelsError(e instanceof Error ? e.message : "Failed to load channels")
      setChannels([])
      setSelectedChannels({})
    } finally {
      setChannelsLoading(false)
    }
  }, [])

  React.useEffect(() => { void loadOrganizations() }, [loadOrganizations])
  React.useEffect(() => {
    if (organizationId) void loadChannels(organizationId)
    else { setChannels([]); setSelectedChannels({}) }
  }, [organizationId, loadChannels])

  const toggleChannel = (id: string) => {
    setSelectedChannels((prev) => ({ ...prev, [id]: !prev[id] }))
  }

  const selectedChannelIds = React.useMemo(
    () => Object.keys(selectedChannels).filter((id) => selectedChannels[id]),
    [selectedChannels],
  )

  const channelsByService = React.useMemo(() => {
    const map: Record<string, BufferChannel[]> = {}
    for (const c of channels) {
      const key = (c.service || "").toLowerCase()
      if (!map[key]) map[key] = []
      map[key].push(c)
    }
    return map
  }, [channels])

  const handlePresetClick = (label: string, minutesFromNow: number) => {
    setScheduleAt(toLocalInputValue(presetToDate(label, minutesFromNow)))
    setAddToQueue(false)
  }

  const handleSchedule = async () => {
    setSubmitError("")
    setResults(null)
    if (!caption.trim()) {
      setSubmitError("No caption to post — generate cards first.")
      return
    }
    if (!selectedChannelIds.length) {
      setSubmitError("Pick at least one channel.")
      return
    }
    let dueAtIso: string | null = null
    if (!addToQueue) {
      const t = Date.parse(scheduleAt)
      if (Number.isNaN(t)) {
        setSubmitError("Pick a valid date and time.")
        return
      }
      if (t <= Date.now()) {
        setSubmitError("Schedule must be in the future.")
        return
      }
      dueAtIso = new Date(t).toISOString()
    }

    // Capture each preview canvas as a PNG blob.
    const blobs: Blob[] = []
    for (let i = 0; i < 4; i++) {
      const c = previewRefs.current[i]
      if (!c) continue
      try {
        const blob = await canvasToBlob(c, "image/png")
        blobs.push(blob)
      } catch (e) {
        // Tainted canvas (CORS-blocked plant photo). Skip rather than fail.
        console.warn("Skipping card", i, "for Buffer post:", e)
      }
    }

    setSubmitting(true)
    try {
      const form = new FormData()
      form.append("text", caption)
      form.append("channelIds", JSON.stringify(selectedChannelIds))
      if (dueAtIso) form.append("dueAt", dueAtIso)
      blobs.forEach((b, i) => {
        form.append("cards", b, `card-${String(i + 1).padStart(2, "0")}.png`)
      })

      const headers = await buildAdminRequestHeaders({ Accept: "application/json" })
      // Don't set Content-Type — let the browser set the multipart boundary
      const resp = await fetch("/api/admin/buffer/post", {
        method: "POST",
        headers,
        body: form,
      })
      const data = await resp.json().catch(() => ({}))
      const list: ScheduleResult[] = Array.isArray(data?.results) ? data.results : []
      setResults(list)
      const allOk = list.length > 0 && list.every((r) => r.ok)
      if (!resp.ok && !list.length) {
        throw new Error(data?.error || `Schedule failed (${resp.status})`)
      }
      if (allOk) {
        fireConfettiBurst()
        setShowSuccess(true)
      } else {
        const failed = list.filter((r) => !r.ok)
        if (failed.length) {
          setSubmitError(`Some posts failed: ${failed.map((f) => f.error || "Unknown").join("; ")}`)
        } else if (!resp.ok) {
          setSubmitError(data?.error || `Schedule failed (${resp.status})`)
        }
      }
    } catch (e) {
      setSubmitError(e instanceof Error ? e.message : "Failed to schedule post")
    } finally {
      setSubmitting(false)
    }
  }

  const cardCount = React.useMemo(() => {
    if (!previewRefs.current) return 0
    return previewRefs.current.filter((c) => !!c).length
  }, [previewRefs])

  return (
    <div className="rounded-2xl border bg-white/90 dark:bg-[#17171a] p-4 space-y-4">
      <div className="flex items-start justify-between gap-3">
        <div>
          <div className="text-xs uppercase tracking-[0.2em] text-stone-500">
            Schedule on social media
          </div>
          <div className="text-xs text-stone-400 mt-0.5">
            Sends the AI caption{plantName ? ` for ${plantName}` : ""} to Instagram, Facebook, or Twitter via Buffer, with the {cardCount || 4} generated cards as media.
          </div>
        </div>
        <Button
          type="button"
          variant="ghost"
          size="sm"
          className="gap-2"
          onClick={() => {
            void loadOrganizations()
            if (organizationId) void loadChannels(organizationId)
          }}
          disabled={orgLoading || channelsLoading}
        >
          <RefreshCw className={`h-4 w-4 ${orgLoading || channelsLoading ? "animate-spin" : ""}`} />
          Refresh
        </Button>
      </div>

      <div className="grid gap-4">
        <div>
          <Label htmlFor="buffer-org" className="mb-1 block text-xs uppercase tracking-wide text-stone-500">
            Buffer organization
          </Label>
          {orgLoading ? (
            <div className="flex items-center gap-2 text-sm text-stone-500">
              <Loader2 className="h-4 w-4 animate-spin" /> Loading organizations...
            </div>
          ) : orgError ? (
            <div className="flex items-start gap-2 rounded-md border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900 dark:border-amber-700 dark:bg-amber-950/40 dark:text-amber-200">
              <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />
              <div>
                <div className="font-medium">Could not load organizations</div>
                <div className="opacity-80">{orgError}</div>
                <div className="mt-1 text-xs opacity-70">Make sure the BUFFER environment variable is set on the server.</div>
              </div>
            </div>
          ) : organizations.length === 0 ? (
            <div className="text-sm text-stone-500">No organizations found.</div>
          ) : (
            <Select
              id="buffer-org"
              value={organizationId}
              onChange={(e) => setOrganizationId(e.target.value)}
            >
              {organizations.map((o) => (
                <option key={o.id} value={o.id}>{o.name || o.id}</option>
              ))}
            </Select>
          )}
        </div>

        <div>
          <Label className="mb-1 block text-xs uppercase tracking-wide text-stone-500">Channels</Label>
          {channelsLoading ? (
            <div className="flex items-center gap-2 text-sm text-stone-500">
              <Loader2 className="h-4 w-4 animate-spin" /> Loading channels...
            </div>
          ) : channelsError ? (
            <div className="flex items-start gap-2 rounded-md border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900 dark:border-amber-700 dark:bg-amber-950/40 dark:text-amber-200">
              <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />
              <div>{channelsError}</div>
            </div>
          ) : channels.length === 0 ? (
            <div className="text-sm text-stone-500">
              No Instagram, Facebook, or Twitter channels are connected to this Buffer organization.
            </div>
          ) : (
            <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">
              {SUPPORTED_SERVICES.map((service) => {
                const list = channelsByService[service] || []
                if (!list.length) return null
                return (
                  <div key={service} className="rounded-lg border border-stone-200 dark:border-stone-700 bg-white dark:bg-[#1a1a1d] p-3">
                    <div className="mb-2 text-[11px] font-semibold uppercase tracking-wide text-stone-500">
                      {SERVICE_LABELS[service]}
                    </div>
                    <div className="space-y-1.5">
                      {list.map((c) => (
                        <label key={c.id} className="flex cursor-pointer items-center gap-2 text-sm">
                          <input
                            type="checkbox"
                            checked={!!selectedChannels[c.id]}
                            onChange={() => toggleChannel(c.id)}
                            className="h-4 w-4 rounded border-input"
                          />
                          <span className="truncate">{c.name}</span>
                        </label>
                      ))}
                    </div>
                  </div>
                )
              })}
            </div>
          )}
        </div>

        <div>
          <Label htmlFor="buffer-schedule-at" className="mb-1 block text-xs uppercase tracking-wide text-stone-500">
            When should it post?
          </Label>
          <div className="mb-3 flex flex-wrap gap-2">
            {SCHEDULE_PRESETS.map((p) => (
              <Button
                key={p.label}
                type="button"
                variant="outline"
                size="sm"
                onClick={() => handlePresetClick(p.label, p.minutesFromNow)}
              >
                {p.label}
              </Button>
            ))}
            <Button
              type="button"
              variant={addToQueue ? "default" : "outline"}
              size="sm"
              onClick={() => setAddToQueue((v) => !v)}
            >
              {addToQueue ? "✓ Add to Buffer queue" : "Add to Buffer queue"}
            </Button>
          </div>
          <div className="flex items-center gap-2">
            <Calendar className="h-4 w-4 text-stone-500" />
            <Input
              id="buffer-schedule-at"
              type="datetime-local"
              value={scheduleAt}
              onChange={(e) => {
                setScheduleAt(e.target.value)
                setAddToQueue(false)
              }}
              disabled={addToQueue}
              className="max-w-xs"
            />
            {addToQueue ? (
              <span className="text-xs text-stone-500">Buffer will pick the next slot in your queue.</span>
            ) : (
              <span className="text-xs text-stone-500">Local time</span>
            )}
          </div>
        </div>

        {submitError && (
          <div className="flex items-start gap-2 rounded-md border border-red-300 bg-red-50 p-3 text-sm text-red-900 dark:border-red-700 dark:bg-red-950/40 dark:text-red-200">
            <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />
            <div>{submitError}</div>
          </div>
        )}

        <div className="flex flex-col-reverse items-stretch justify-between gap-2 sm:flex-row sm:items-center">
          <div className="text-xs text-stone-500 inline-flex items-center gap-1.5">
            <ImageIcon className="h-3.5 w-3.5" />
            {cardCount} card{cardCount === 1 ? "" : "s"} attached · {selectedChannelIds.length} channel{selectedChannelIds.length === 1 ? "" : "s"} selected
          </div>
          <Button
            onClick={() => void handleSchedule()}
            disabled={submitting || disabled || !selectedChannelIds.length || !caption.trim()}
            className="gap-2"
          >
            {submitting ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}
            {submitting ? "Scheduling..." : "Schedule on Buffer"}
          </Button>
        </div>
      </div>

      <Dialog open={showSuccess} onOpenChange={setShowSuccess}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <CheckCircle2 className="h-5 w-5 text-emerald-500" />
              Scheduled!
            </DialogTitle>
          </DialogHeader>
          <div className="space-y-2 text-sm">
            <p>
              Your post was scheduled successfully on {results?.length || 0} channel
              {(results?.length || 0) === 1 ? "" : "s"}.
            </p>
            {results && results.length > 0 && (
              <ul className="space-y-1 rounded-md bg-stone-100 dark:bg-stone-800/60 p-3 text-xs">
                {results.map((r, i) => {
                  const ch = channels.find((c) => c.id === r.channelId)
                  const when = r.post?.dueAt ? new Date(r.post.dueAt).toLocaleString() : "Queued"
                  return (
                    <li key={`${r.channelId}-${i}`} className="flex items-center justify-between gap-2">
                      <span className="truncate">{ch ? `${SERVICE_LABELS[ch.service] || ch.service} · ${ch.name}` : r.channelId}</span>
                      <span className="text-stone-500">{when}</span>
                    </li>
                  )
                })}
              </ul>
            )}
          </div>
          <DialogFooter>
            <Button onClick={() => setShowSuccess(false)}>Done</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}

export default AdminExportBufferSchedule
