#!/usr/bin/env bash
set -euo pipefail

# Setup PlantSwipe server so Admin Pull & Build works non-interactively
# - Makes repository writable by the service user (avoids sudo for git)
# - Grants minimal NOPASSWD sudo to reload nginx and restart services
#
# Usage (as root):
#   sudo bash ./scripts/setup-plantswipe.sh
#
# Tunables via env:
#   PLANTSWIPE_REPO_DIR   (default: /var/www/PlantSwipe)
#   PLANTSWIPE_SERVICE_USER (default: www-data)
#   PLANTSWIPE_NODE_SERVICE (default: plant-swipe-node)
#   PLANTSWIPE_ADMIN_SERVICE (default: admin-api)
#   NGINX_SERVICE           (default: nginx)

log() { printf "[%s] %s\n" "$(date -u +'%Y-%m-%dT%H:%M:%SZ')" "$*"; }

if [[ $EUID -ne 0 ]]; then
  echo "[ERROR] Run as root: sudo bash $0" >&2
  exit 1
fi

REPO_ROOT="${PLANTSWIPE_REPO_DIR:-/var/www/PlantSwipe}"
SERVICE_USER="${PLANTSWIPE_SERVICE_USER:-www-data}"
NODE_SERVICE="${PLANTSWIPE_NODE_SERVICE:-plant-swipe-node}"
ADMIN_SERVICE="${PLANTSWIPE_ADMIN_SERVICE:-admin-api}"
NGINX_SERVICE="${NGINX_SERVICE:-nginx}"

# Resolve repo root if the provided path is the nested app dir
if [[ ! -d "$REPO_ROOT/.git" ]]; then
  if command -v git >/dev/null 2>&1; then
    TOP=$(git -C "$REPO_ROOT" rev-parse --show-toplevel 2>/dev/null || true)
    if [[ -n "$TOP" && -d "$TOP/.git" ]]; then
      REPO_ROOT="$TOP"
    fi
  fi
fi

# Basic validation
if ! id -u "$SERVICE_USER" >/dev/null 2>&1; then
  echo "[ERROR] Service user '$SERVICE_USER' does not exist." >&2
  exit 1
fi
if [[ ! -d "$REPO_ROOT" ]]; then
  echo "[ERROR] Repository directory not found: $REPO_ROOT" >&2
  exit 1
fi
if [[ ! -d "$REPO_ROOT/.git" ]]; then
  echo "[ERROR] .git directory not found in repo: $REPO_ROOT" >&2
  exit 1
fi

log "Config: repo=$REPO_ROOT user=$SERVICE_USER node_service=$NODE_SERVICE admin_service=$ADMIN_SERVICE nginx_service=$NGINX_SERVICE"

# One-time: ensure repo is writable by service user (git operations)
if command -v chattr >/dev/null 2>&1; then
  chattr -Ri "$REPO_ROOT/.git" || true
fi
log "Changing ownership of repository to $SERVICE_USER..."
chown -R "$SERVICE_USER:$SERVICE_USER" "$REPO_ROOT"
chmod -R u+rwX "$REPO_ROOT/.git"

# Compute absolute paths for sudoers commands
SYSTEMCTL_BIN="$(command -v systemctl || echo /bin/systemctl)"
NGINX_BIN="$(command -v nginx || echo /usr/sbin/nginx)"

SUDOERS_FILE="/etc/sudoers.d/plantswipe"
log "Writing sudoers rules to $SUDOERS_FILE ..."
cat > "$SUDOERS_FILE" <<EOF
# Auto-generated by setup-plantswipe.sh
# Allow service user to restart PlantSwipe and reload nginx without password
$SERVICE_USER ALL=(root) NOPASSWD: $NGINX_BIN -t
$SERVICE_USER ALL=(root) NOPASSWD: $SYSTEMCTL_BIN reload $NGINX_SERVICE
$SERVICE_USER ALL=(root) NOPASSWD: $SYSTEMCTL_BIN restart $NODE_SERVICE
$SERVICE_USER ALL=(root) NOPASSWD: $SYSTEMCTL_BIN restart $ADMIN_SERVICE
EOF
chmod 0440 "$SUDOERS_FILE"

# Validate sudoers
if ! visudo -cf "$SUDOERS_FILE" >/dev/null 2>&1; then
  echo "[ERROR] visudo validation failed for $SUDOERS_FILE" >&2
  exit 1
fi
log "sudoers installed and validated."

# Mark repo safe for both root and service user to avoid 'dubious ownership'
log "Marking repo as safe in git config (root and $SERVICE_USER)..."
sudo -u "$SERVICE_USER" -H git config --global --add safe.directory "$REPO_ROOT" || true
git config --global --add safe.directory "$REPO_ROOT" || true

# Quick checks
log "Quick checks:"
log "- systemctl version: $($SYSTEMCTL_BIN --version | head -n1 2>/dev/null || echo 'n/a')"
log "- nginx version: $($NGINX_BIN -v 2>&1 || echo 'n/a')"
log "- repo owner: $(stat -c '%U' "$REPO_ROOT" 2>/dev/null)"
log "- .git owner: $(stat -c '%U' "$REPO_ROOT/.git" 2>/dev/null)"

log "Done. You can now use the Admin Pull & Build and Restart."