#!/bin/bash

# Sync Email Template Script
# Copies the shared email template from frontend to Supabase edge functions
# AND generates a plain .mjs version for Node.js (which cannot import .ts)
#
# Run this after making changes to src/lib/emailTemplateShared.ts

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

SOURCE_FILE="$PROJECT_ROOT/src/lib/emailTemplateShared.ts"
DEST_DIR="$PROJECT_ROOT/supabase/functions/_shared"
DEST_FILE="$DEST_DIR/emailTemplateShared.ts"
MJS_FILE="$PROJECT_ROOT/src/lib/emailTemplateShared.mjs"

# ── 1. Copy .ts → Supabase edge functions ────────────────────────────────────
mkdir -p "$DEST_DIR"
cp "$SOURCE_FILE" "$DEST_FILE"

echo "✅ Synced email template to Supabase functions"
echo "   Source: $SOURCE_FILE"
echo "   Dest:   $DEST_FILE"

# ── 2. Generate .mjs for Node.js (strip TypeScript syntax) ───────────────────
# Ensure the output file exists and is writable (fix Permission denied when running as www-data)
touch "$MJS_FILE" 2>/dev/null || true
node -e "
const fs = require('fs');
let code = fs.readFileSync('$SOURCE_FILE', 'utf8');

// Remove 'export type ...' lines
code = code.replace(/^export type .*$/gm, '');

// Remove 'export interface ... { ... }' blocks (multiline)
code = code.replace(/^export interface \w+\s*\{[^}]*\}/gm, '');

// Remove multiline Record<> type annotations on const:
//   : Record<SupportedLanguage, {\n  ...\n}> = {  →  = {
code = code.replace(/: Record<[^{]*\{[^}]*\}>\s*=/g, ' =');

// Remove simple type annotations on const (e.g. : SupportedLanguage)
code = code.replace(/^(export const \w+): \w+ =/gm, '\$1 =');

// Remove function return types  ): string {  →  ) {
code = code.replace(/\): \w+ \{/g, ') {');

// Remove parameter type annotations  (param: Type =  →  (param =
code = code.replace(/(\w): \w+(\[\])? =/g, '\$1 =');
// (param: Type,  →  (param,
code = code.replace(/(\w): \w+(\[\])?,/g, '\$1,');
// (param: Type)  →  (param)
code = code.replace(/(\w): \w+(\[\])?\)/g, '\$1)');

// Clean up empty lines left over
code = code.replace(/\n{3,}/g, '\n\n');

fs.writeFileSync('$MJS_FILE.tmp', code);
" 2>&1

# Add header comment
{
  echo "// Auto-generated JS version of emailTemplateShared.ts — DO NOT EDIT THIS FILE DIRECTLY"
  echo "// Run: npm run sync-email-template"
  echo ""
  cat "$MJS_FILE.tmp"
} > "$MJS_FILE"
rm -f "$MJS_FILE.tmp"

echo "✅ Generated .mjs version for Node.js"
echo "   Dest:   $MJS_FILE"

# Validate syntax with Node.js
if node --check "$MJS_FILE" 2>/dev/null; then
  echo "✅ .mjs syntax check passed"
else
  echo "❌ .mjs syntax check FAILED — please fix manually"
  echo "   Run: node --check $MJS_FILE"
  exit 1
fi

echo ""
echo "⚠️  Remember to redeploy the edge function after syncing:"
echo "   supabase functions deploy email-campaign-runner"
